// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/history" | "/landing" | "/login" | "/onboarding" | "/pricing" | "/privacy" | "/settings" | "/signup" | "/subscribe" | "/subscribe/fail" | "/subscribe/success" | "/terms" | "/write"
type AppRouteHandlerRoutes = "/api/check-blog-index" | "/api/cron/check-naver-rank" | "/api/generate" | "/api/generate-titles" | "/api/payments/confirm" | "/api/recommend-keywords" | "/api/tracking/sync" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/subscribe"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/check-blog-index": {}
  "/api/cron/check-naver-rank": {}
  "/api/generate": {}
  "/api/generate-titles": {}
  "/api/payments/confirm": {}
  "/api/recommend-keywords": {}
  "/api/tracking/sync": {}
  "/auth/callback": {}
  "/history": {}
  "/landing": {}
  "/login": {}
  "/onboarding": {}
  "/pricing": {}
  "/privacy": {}
  "/settings": {}
  "/signup": {}
  "/subscribe": {}
  "/subscribe/fail": {}
  "/subscribe/success": {}
  "/terms": {}
  "/write": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/subscribe": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
